version: '3'
services:
  api-e2e:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - ENVIRONMENT=test
    ports:
      - '8080:8080'
    working_dir: /app
    depends_on:
      - mongo       
    command: ["yarn", "run", "start:dev"]

  mongo:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test
    ports:
      - '27017:27017'      

  e2e-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      API_BASE_URL: 'http://api-e2e:8080'
    ports:
    - '5001-5005'
    depends_on:
      - api-e2e
      - mongo